/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;


import java.util.List;
import sistema_gestion_alumnos.modelo.Alumno;
import sistema_gestion_alumnos.modelo.AlumnoData;
import sistema_gestion_alumnos.modelo.Conexion;

/**
 *
 * @author Lucas
 */
public class abmAlumnos extends javax.swing.JInternalFrame {

    /**
     * Creates new form abmAlumnos
     */
    
    private AlumnoData alumnoData;
    private Conexion con;
    
    public abmAlumnos() {
        initComponents();
        
        con = new Conexion();
        alumnoData = new AlumnoData(con);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        PanelCabecera = new javax.swing.JPanel();
        btnModificar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnCargar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPCargar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jActivoCargar = new javax.swing.JToggleButton();
        jdcFechaNacimiento = new com.toedter.calendar.JDateChooser();
        jPModificar = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cbAlumnoModificar = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jtMostrarFechaNac = new javax.swing.JLabel();
        btnActivo = new javax.swing.JToggleButton();
        jtMostrarNombre = new javax.swing.JTextField();
        jdcFechaNac = new com.toedter.calendar.JDateChooser();
        jButton2 = new javax.swing.JButton();
        jPBorrar = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        cbListaAlumnos = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        tfBuscarId = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        rbLista = new javax.swing.JRadioButton();
        rbID = new javax.swing.JRadioButton();
        panelNombreCompleto = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        lbNombreCompleto = new javax.swing.JLabel();
        BtnBorrarAlumno = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jbBuscar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(750, 427));

        PanelCabecera.setBackground(new java.awt.Color(67, 119, 202));
        PanelCabecera.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnModificar.setText("Modificar");
        btnModificar.setMaximumSize(new java.awt.Dimension(65, 23));
        btnModificar.setMinimumSize(new java.awt.Dimension(65, 23));
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarbtnCargarActionPerformed(evt);
            }
        });

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarbtnCargarActionPerformed(evt);
            }
        });

        btnCargar.setText("Cargar");
        btnCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelCabeceraLayout = new javax.swing.GroupLayout(PanelCabecera);
        PanelCabecera.setLayout(PanelCabeceraLayout);
        PanelCabeceraLayout.setHorizontalGroup(
            PanelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCabeceraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCargar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 179, Short.MAX_VALUE)
                .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(174, 174, 174)
                .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PanelCabeceraLayout.setVerticalGroup(
            PanelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCabeceraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCargar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBorrar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new java.awt.CardLayout());

        jPCargar.setPreferredSize(new java.awt.Dimension(516, 331));

        jLabel1.setText("Nombre completo:");

        jLabel2.setText("Fecha de Nacimiento:");

        jLabel3.setText("Activo:");

        jButton1.setText("Cargar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jActivoCargar.setText("Activo");
        jActivoCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jActivoCargarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPCargarLayout = new javax.swing.GroupLayout(jPCargar);
        jPCargar.setLayout(jPCargarLayout);
        jPCargarLayout.setHorizontalGroup(
            jPCargarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCargarLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(jPCargarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPCargarLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 163, Short.MAX_VALUE)
                        .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPCargarLayout.createSequentialGroup()
                        .addGroup(jPCargarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPCargarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jActivoCargar, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jdcFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(82, 82, 82))
        );
        jPCargarLayout.setVerticalGroup(
            jPCargarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCargarLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPCargarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPCargarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jdcFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPCargarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jActivoCargar))
                .addGap(99, 99, 99)
                .addComponent(jButton1)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jPanel1.add(jPCargar, "card2");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Seleccione alumno a modificar:");

        cbAlumnoModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAlumnoModificarActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel9.setText("Nombre completo:");

        jLabel10.setText("Fecha de Nacimiento:");

        jLabel11.setText("Activo:");

        btnActivo.setText("Activo");
        btnActivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActivoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(74, 74, 74)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnActivo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                    .addComponent(jtMostrarNombre)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jtMostrarFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jdcFechaNac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtMostrarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                    .addComponent(jtMostrarFechaNac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jdcFechaNac, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActivo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton2.setText("Actualizar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPModificarLayout = new javax.swing.GroupLayout(jPModificar);
        jPModificar.setLayout(jPModificarLayout);
        jPModificarLayout.setHorizontalGroup(
            jPModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPModificarLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(jPModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPModificarLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addComponent(cbAlumnoModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(91, 91, 91))
        );
        jPModificarLayout.setVerticalGroup(
            jPModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPModificarLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbAlumnoModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        jPanel1.add(jPModificar, "card4");

        jPBorrar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPBorrarFocusLost(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Seleccione el alumno a borrar:");

        cbListaAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbListaAlumnosActionPerformed(evt);
            }
        });

        jLabel6.setText("O si conoce el id: ");

        tfBuscarId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBuscarIdActionPerformed(evt);
            }
        });
        tfBuscarId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfBuscarIdKeyTyped(evt);
            }
        });

        jLabel7.setText("Seleccionar desde lista");

        rbLista.setSelected(true);
        rbLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbListaActionPerformed(evt);
            }
        });

        rbID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbIDActionPerformed(evt);
            }
        });

        panelNombreCompleto.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel8.setText("Nombre del alumno:");

        javax.swing.GroupLayout panelNombreCompletoLayout = new javax.swing.GroupLayout(panelNombreCompleto);
        panelNombreCompleto.setLayout(panelNombreCompletoLayout);
        panelNombreCompletoLayout.setHorizontalGroup(
            panelNombreCompletoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNombreCompletoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(lbNombreCompleto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelNombreCompletoLayout.setVerticalGroup(
            panelNombreCompletoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNombreCompletoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelNombreCompletoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lbNombreCompleto))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BtnBorrarAlumno.setText("Borrar");
        BtnBorrarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBorrarAlumnoActionPerformed(evt);
            }
        });

        jLabel12.setText("ID:");

        jbBuscar.setText("Buscar");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPBorrarLayout = new javax.swing.GroupLayout(jPBorrar);
        jPBorrar.setLayout(jPBorrarLayout);
        jPBorrarLayout.setHorizontalGroup(
            jPBorrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBorrarLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(jPBorrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPBorrarLayout.createSequentialGroup()
                        .addComponent(rbLista)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelNombreCompleto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnBorrarAlumno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbListaAlumnos, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPBorrarLayout.createSequentialGroup()
                        .addComponent(rbID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addGap(205, 205, 205)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfBuscarId, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        jPBorrarLayout.setVerticalGroup(
            jPBorrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBorrarLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPBorrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rbLista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(5, 5, 5)
                .addComponent(cbListaAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(jPBorrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbID)
                    .addGroup(jPBorrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfBuscarId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)
                        .addComponent(jbBuscar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelNombreCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(BtnBorrarAlumno)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jPanel1.add(jPBorrar, "card3");

        jButton3.setText("Cerrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelCabecera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelCabecera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 316, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(60, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(37, 37, 37)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModificarbtnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarbtnCargarActionPerformed
        if ( evt.getSource()== btnCargar ){
            jPBorrar.setVisible(false);
            jPCargar.setVisible(true);
            jPModificar.setVisible(false);
        }
        else if ( evt.getSource()== btnBorrar ){
            jPBorrar.setVisible(true);
            jPCargar.setVisible(false);
            jPModificar.setVisible(false);
        }
        else if ( evt.getSource()== btnModificar){
            jPBorrar.setVisible(false);
            jPCargar.setVisible(false);
            jPModificar.setVisible(true);
            List<Alumno> alumnos = alumnoData.obtenerAlumnos();
            boolean control;
            for(Alumno alumno : alumnos){
                control=true;
                for(int i=0;i<cbAlumnoModificar.getItemCount();i++){
                    if(Integer.parseInt(cbAlumnoModificar.getItemAt(i)) == alumno.getId()){
                        control=false;
                    }
                }
                if(control){
                    cbAlumnoModificar.addItem(String.valueOf(alumno.getId()));
                }
            }
        }
    }//GEN-LAST:event_btnModificarbtnCargarActionPerformed

    private void btnBorrarbtnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarbtnCargarActionPerformed
        if ( evt.getSource()== btnCargar ){
            jPBorrar.setVisible(false);
            jPCargar.setVisible(true);
            jPModificar.setVisible(false);
        }
        else if ( evt.getSource()== btnBorrar ){
            jPBorrar.setVisible(true);
            jPCargar.setVisible(false);
            jPModificar.setVisible(false);
            List<Alumno> alumnos = alumnoData.obtenerAlumnos();
            boolean control;
            for(Alumno alumno : alumnos){
                control=true;
                for(int i=0;i<cbListaAlumnos.getItemCount();i++){
                    if(Integer.parseInt(cbListaAlumnos.getItemAt(i)) == alumno.getId()){
                        control=false;
                    }
                }
                if(control){
                    cbListaAlumnos.addItem(String.valueOf(alumno.getId()));
                }
            }
            rbID.setSelected(false);
            cbListaAlumnos.setEnabled(true);
            tfBuscarId.setEnabled(false);
            jbBuscar.setEnabled(false);
        }
        else if ( evt.getSource()== btnModificar){
            jPBorrar.setVisible(false);
            jPCargar.setVisible(false);
            jPModificar.setVisible(true);
        }
    }//GEN-LAST:event_btnBorrarbtnCargarActionPerformed

    private void btnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarActionPerformed
        if ( evt.getSource()== btnCargar ){
            jPBorrar.setVisible(false);
            jPCargar.setVisible(true);
            jPModificar.setVisible(false);
        }
        else if ( evt.getSource()== btnBorrar ){
            jPBorrar.setVisible(true);
            jPCargar.setVisible(false);
            jPModificar.setVisible(false);
        }
        else if ( evt.getSource()== btnModificar){
            jPBorrar.setVisible(false);
            jPCargar.setVisible(false);
            jPModificar.setVisible(true);
        }
    }//GEN-LAST:event_btnCargarActionPerformed

    private void jActivoCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jActivoCargarActionPerformed
        if (jActivoCargar.isSelected()){
            jActivoCargar.setText("Inactivo");
        }else{
            jActivoCargar.setText("Activo");
        }
    }//GEN-LAST:event_jActivoCargarActionPerformed

    private void rbListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbListaActionPerformed
        if (rbLista.isSelected()){
            rbID.setSelected(false);
            cbListaAlumnos.setEnabled(true);
            tfBuscarId.setEnabled(false);
            jbBuscar.setEnabled(false);
        }
    }//GEN-LAST:event_rbListaActionPerformed

    private void rbIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbIDActionPerformed
        if (rbID.isSelected()){
            rbLista.setSelected(false);
            cbListaAlumnos.setEnabled(false);
            panelNombreCompleto.setVisible(true);
            tfBuscarId.setEnabled(true);
            jbBuscar.setEnabled(true);
        }
    }//GEN-LAST:event_rbIDActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.hide();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nombre = jtNombre.getText();
        java.sql.Date fecha_nacimiento = new java.sql.Date(jdcFechaNacimiento.getCalendar().getTimeInMillis());
        boolean activo = "Activo".equals(jActivoCargar.getText());
        Alumno alumno = new Alumno(activo,fecha_nacimiento,nombre);
        alumnoData.guardarAlumno(alumno);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbListaAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbListaAlumnosActionPerformed
        Alumno alumno;
        String selectedValue = cbListaAlumnos.getSelectedItem().toString();
        alumno=alumnoData.buscarAlumno(Integer.parseInt(selectedValue));
        lbNombreCompleto.setText(alumno.getNombre_completo());
    }//GEN-LAST:event_cbListaAlumnosActionPerformed

    private void BtnBorrarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBorrarAlumnoActionPerformed
        if(rbLista.isSelected()){
            String selectedValue = cbListaAlumnos.getSelectedItem().toString();
            alumnoData.borrarAlumno(Integer.parseInt(selectedValue));
            cbListaAlumnos.removeItemAt(cbListaAlumnos.getSelectedIndex()); 
        }
        else if(rbID.isSelected()){
            alumnoData.borrarAlumno(Integer.parseInt(tfBuscarId.getText()));
        }
    }//GEN-LAST:event_BtnBorrarAlumnoActionPerformed

    private void tfBuscarIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBuscarIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfBuscarIdActionPerformed

    private void tfBuscarIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfBuscarIdKeyTyped
        
        
    }//GEN-LAST:event_tfBuscarIdKeyTyped

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        Alumno alumno;
        if(rbID.isSelected()){
            alumno=alumnoData.buscarAlumno(Integer.parseInt(tfBuscarId.getText()));
            if(alumno == null){
                lbNombreCompleto.setText("No se encontro alumno con ese ID.");
            }
            else{
                lbNombreCompleto.setText(alumno.getNombre_completo());
            }
        }
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jPBorrarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPBorrarFocusLost

    }//GEN-LAST:event_jPBorrarFocusLost

    private void cbAlumnoModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAlumnoModificarActionPerformed
        jtMostrarNombre.setText(alumnoData.buscarAlumno(Integer.parseInt(cbAlumnoModificar.getSelectedItem().toString())).getNombre_completo());
        jtMostrarFechaNac.setText(alumnoData.buscarAlumno(Integer.parseInt(cbAlumnoModificar.getSelectedItem().toString())).getNacimiento_alumno().toString());
        if(alumnoData.buscarAlumno(Integer.parseInt(cbAlumnoModificar.getSelectedItem().toString())).isActivo()){
            btnActivo.setText("Activo");
        }
        else
            btnActivo.setText("Inactivo");
    }//GEN-LAST:event_cbAlumnoModificarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String nombre = jtMostrarNombre.getText();
        java.sql.Date fecha_nacimiento = new java.sql.Date(jdcFechaNac.getCalendar().getTimeInMillis());
        boolean activo = "Activo".equals(btnActivo.getText());
        int id = Integer.parseInt(cbAlumnoModificar.getSelectedItem().toString());
        Alumno alumno = new Alumno(activo,fecha_nacimiento,nombre,id);
        alumnoData.actualizarAlumno(alumno);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnActivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActivoActionPerformed
        if(btnActivo.isSelected()== true){
            btnActivo.setText("Activo");
            btnActivo.setSelected(true);
        }
        else if(btnActivo.isSelected()==false){
            btnActivo.setText("Inactivo");
            btnActivo.setSelected(false);
        }
    }//GEN-LAST:event_btnActivoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBorrarAlumno;
    private javax.swing.JPanel PanelCabecera;
    private javax.swing.JToggleButton btnActivo;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnCargar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox<String> cbAlumnoModificar;
    private javax.swing.JComboBox<String> cbListaAlumnos;
    private javax.swing.JToggleButton jActivoCargar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPBorrar;
    private javax.swing.JPanel jPCargar;
    private javax.swing.JPanel jPModificar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jbBuscar;
    private com.toedter.calendar.JDateChooser jdcFechaNac;
    private com.toedter.calendar.JDateChooser jdcFechaNacimiento;
    private javax.swing.JLabel jtMostrarFechaNac;
    private javax.swing.JTextField jtMostrarNombre;
    private javax.swing.JTextField jtNombre;
    private javax.swing.JLabel lbNombreCompleto;
    private javax.swing.JPanel panelNombreCompleto;
    private javax.swing.JRadioButton rbID;
    private javax.swing.JRadioButton rbLista;
    private javax.swing.JTextField tfBuscarId;
    // End of variables declaration//GEN-END:variables
}
