/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.util.List;
import sistema_gestion_alumnos.modelo.Conexion;
import sistema_gestion_alumnos.modelo.Materia;
import sistema_gestion_alumnos.modelo.MateriaData;

/**
 *
 * @author Lucas
 */
public class abmMaterias extends javax.swing.JInternalFrame {

    /**
     * Creates new form abmMaterias
     */
    
    private MateriaData materiaData;
    private Conexion con;
    
    public abmMaterias() {
        initComponents();
        
        con = new Conexion();
        materiaData = new MateriaData(con);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelCabecera = new javax.swing.JPanel();
        btnModificar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnCargar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPBorrar = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        cbListaMaterias = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        tfBuscarId = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        rbLista = new javax.swing.JRadioButton();
        rbID = new javax.swing.JRadioButton();
        panelNombreCompleto = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        lbNombreCompleto = new javax.swing.JLabel();
        BtnBorrarAlumno = new javax.swing.JButton();
        jbBuscar = new javax.swing.JButton();
        jPCargar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtNombreMateria = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jlId = new javax.swing.JLabel();
        jPModificar = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cbMaterias = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jMostrarNombre = new javax.swing.JTextField();
        jlIdModificar = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        PanelCabecera.setBackground(new java.awt.Color(67, 119, 202));
        PanelCabecera.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarbtnCargarActionPerformed(evt);
            }
        });

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarbtnCargarActionPerformed(evt);
            }
        });

        btnCargar.setText("Cargar");
        btnCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelCabeceraLayout = new javax.swing.GroupLayout(PanelCabecera);
        PanelCabecera.setLayout(PanelCabeceraLayout);
        PanelCabeceraLayout.setHorizontalGroup(
            PanelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCabeceraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCargar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                .addGap(74, 74, 74)
                .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PanelCabeceraLayout.setVerticalGroup(
            PanelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCabeceraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModificar)
                    .addComponent(btnCargar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBorrar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton3.setText("Cerrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new java.awt.CardLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Seleccione la materia a borrar:");

        cbListaMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbListaMateriasActionPerformed(evt);
            }
        });

        jLabel6.setText("O si conoce el id: ");

        tfBuscarId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBuscarIdActionPerformed(evt);
            }
        });

        jLabel7.setText("Seleccionar desde lista");

        rbLista.setSelected(true);
        rbLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbListaActionPerformed(evt);
            }
        });

        rbID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbIDActionPerformed(evt);
            }
        });

        panelNombreCompleto.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel8.setText("Nombre de la materia:");

        javax.swing.GroupLayout panelNombreCompletoLayout = new javax.swing.GroupLayout(panelNombreCompleto);
        panelNombreCompleto.setLayout(panelNombreCompletoLayout);
        panelNombreCompletoLayout.setHorizontalGroup(
            panelNombreCompletoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNombreCompletoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbNombreCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelNombreCompletoLayout.setVerticalGroup(
            panelNombreCompletoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNombreCompletoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelNombreCompletoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbNombreCompleto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelNombreCompletoLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        BtnBorrarAlumno.setText("Borrar");
        BtnBorrarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBorrarAlumnoActionPerformed(evt);
            }
        });

        jbBuscar.setText("Buscar");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPBorrarLayout = new javax.swing.GroupLayout(jPBorrar);
        jPBorrar.setLayout(jPBorrarLayout);
        jPBorrarLayout.setHorizontalGroup(
            jPBorrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBorrarLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPBorrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPBorrarLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 332, Short.MAX_VALUE))
                    .addGroup(jPBorrarLayout.createSequentialGroup()
                        .addGroup(jPBorrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rbLista)
                            .addComponent(rbID))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPBorrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPBorrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbListaMaterias, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPBorrarLayout.createSequentialGroup()
                                .addComponent(tfBuscarId, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(jPBorrarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPBorrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnBorrarAlumno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelNombreCompleto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPBorrarLayout.setVerticalGroup(
            jPBorrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBorrarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPBorrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPBorrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbListaMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(rbLista))
                .addGap(30, 30, 30)
                .addGroup(jPBorrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbID)
                    .addGroup(jPBorrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfBuscarId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbBuscar)))
                .addGap(18, 18, 18)
                .addComponent(panelNombreCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnBorrarAlumno)
                .addGap(23, 23, 23))
        );

        jPanel1.add(jPBorrar, "card3");

        jPCargar.setPreferredSize(new java.awt.Dimension(516, 331));

        jLabel1.setText("Nombre de la materia:");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ID:");

        jButton1.setText("Cargar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPCargarLayout = new javax.swing.GroupLayout(jPCargar);
        jPCargar.setLayout(jPCargarLayout);
        jPCargarLayout.setHorizontalGroup(
            jPCargarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCargarLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPCargarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPCargarLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addGroup(jPCargarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPCargarLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlId))
                            .addComponent(jtNombreMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPCargarLayout.setVerticalGroup(
            jPCargarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCargarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPCargarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtNombreMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPCargarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlId))
                .addGap(19, 19, 19)
                .addComponent(jButton1)
                .addContainerGap(116, Short.MAX_VALUE))
        );

        jPanel1.add(jPCargar, "card2");

        jLabel4.setText("Seleccione materia a modificar:");

        cbMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMateriasActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel9.setText("Nombre materia:");

        jLabel11.setText("Id de Materia: ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jMostrarNombre)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlIdModificar)
                        .addGap(0, 212, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jMostrarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlIdModificar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton2.setText("Actualizar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPModificarLayout = new javax.swing.GroupLayout(jPModificar);
        jPModificar.setLayout(jPModificarLayout);
        jPModificarLayout.setHorizontalGroup(
            jPModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPModificarLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPModificarLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(38, 38, 38)
                        .addComponent(cbMaterias, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );
        jPModificarLayout.setVerticalGroup(
            jPModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPModificarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        jPanel1.add(jPModificar, "card4");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelCabecera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelCabecera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModificarbtnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarbtnCargarActionPerformed
        if ( evt.getSource()== btnCargar ){
            jPBorrar.setVisible(false);
            jPCargar.setVisible(true);
            jPModificar.setVisible(false);
        }
        else if ( evt.getSource()== btnBorrar ){
            jPBorrar.setVisible(true);
            jPCargar.setVisible(false);
            jPModificar.setVisible(false);
        }
        else if ( evt.getSource()== btnModificar){
            jPBorrar.setVisible(false);
            jPCargar.setVisible(false);
            jPModificar.setVisible(true);
            List<Materia> materias = materiaData.obtenerMaterias();
            boolean control;
            for(Materia materia : materias){
                control=true;
                for(int i=0;i<cbMaterias.getItemCount();i++){
                    if(Integer.parseInt(cbMaterias.getItemAt(i)) == materia.getId()){
                        control=false;
                    }
                }
                if(control){
                    cbMaterias.addItem(String.valueOf(materia.getId()));
                }
            }
        }
    }//GEN-LAST:event_btnModificarbtnCargarActionPerformed

    private void btnBorrarbtnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarbtnCargarActionPerformed
        if ( evt.getSource()== btnCargar ){
            jPBorrar.setVisible(false);
            jPCargar.setVisible(true);
            jPModificar.setVisible(false);
        }
        else if ( evt.getSource()== btnBorrar ){
            jPBorrar.setVisible(true);
            jPCargar.setVisible(false);
            jPModificar.setVisible(false);
            List<Materia> materias = materiaData.obtenerMaterias();
            boolean control;
            for(Materia materia : materias){
                control=true;
                for(int i=0;i<cbListaMaterias.getItemCount();i++){
                    if(Integer.parseInt(cbListaMaterias.getItemAt(i)) == materia.getId()){
                        control=false;
                    }
                }
                if(control){
                    cbListaMaterias.addItem(String.valueOf(materia.getId()));
                }
            }
        }
        else if ( evt.getSource()== btnModificar){
            jPBorrar.setVisible(false);
            jPCargar.setVisible(false);
            jPModificar.setVisible(true);
        }
    }//GEN-LAST:event_btnBorrarbtnCargarActionPerformed

    private void btnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarActionPerformed
        if ( evt.getSource()== btnCargar ){
            jPBorrar.setVisible(false);
            jPCargar.setVisible(true);
            jPModificar.setVisible(false);
        }
        else if ( evt.getSource()== btnBorrar ){
            jPBorrar.setVisible(true);
            jPCargar.setVisible(false);
            jPModificar.setVisible(false);
        }
        else if ( evt.getSource()== btnModificar){
            jPBorrar.setVisible(false);
            jPCargar.setVisible(false);
            jPModificar.setVisible(true);
        }
    }//GEN-LAST:event_btnCargarActionPerformed

    private void rbListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbListaActionPerformed
        if (rbLista.isSelected()){
            rbID.setSelected(false);
            cbListaMaterias.setEnabled(true);
            tfBuscarId.setEnabled(false);
            jbBuscar.setEnabled(false);
        }
    }//GEN-LAST:event_rbListaActionPerformed

    private void rbIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbIDActionPerformed
        if (rbID.isSelected()){
            rbLista.setSelected(false);
            cbListaMaterias.setEnabled(false);
            panelNombreCompleto.setVisible(true);
            tfBuscarId.setEnabled(true);
            jbBuscar.setEnabled(true);
        }
    }//GEN-LAST:event_rbIDActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.hide();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nombre = jtNombreMateria.getText();
        Materia materia = new Materia(nombre);
        materiaData.guardarMateria(materia);
        jlId.setText(String.valueOf(materia.getId()));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMateriasActionPerformed
        Materia materia = materiaData.buscarMateria(Integer.parseInt(cbMaterias.getSelectedItem().toString()));
        jMostrarNombre.setText(materia.getNombre());
        jlIdModificar.setText(String.valueOf(materia.getId()));
    }//GEN-LAST:event_cbMateriasActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String nombre = jMostrarNombre.getText();
        int id = Integer.parseInt(jlIdModificar.getText());
        Materia materia = new Materia(nombre,id);
        materiaData.actualizarMateria(materia);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cbListaMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbListaMateriasActionPerformed
        lbNombreCompleto.setText(materiaData.buscarMateria(Integer.parseInt(cbListaMaterias.getSelectedItem().toString())).getNombre());
    }//GEN-LAST:event_cbListaMateriasActionPerformed

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        Materia materia = materiaData.buscarMateria(Integer.parseInt(tfBuscarId.getText()));
        if(materia != null){
            lbNombreCompleto.setText(materiaData.buscarMateria(Integer.parseInt(tfBuscarId.getText())).getNombre());
        }
        else{
            lbNombreCompleto.setText("No se encuentra la materia con ese ID.");
        }
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void tfBuscarIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBuscarIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfBuscarIdActionPerformed

    private void BtnBorrarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBorrarAlumnoActionPerformed
        if(rbLista.isSelected()){
            String selectedValue = cbListaMaterias.getSelectedItem().toString();
            materiaData.borrarMateria(Integer.parseInt(selectedValue));
            cbListaMaterias.removeItemAt(cbListaMaterias.getSelectedIndex()); 
        }
        else if(rbID.isSelected()){
            materiaData.borrarMateria(Integer.parseInt(tfBuscarId.getText()));
        }
    }//GEN-LAST:event_BtnBorrarAlumnoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBorrarAlumno;
    private javax.swing.JPanel PanelCabecera;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnCargar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox<String> cbListaMaterias;
    private javax.swing.JComboBox<String> cbMaterias;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jMostrarNombre;
    private javax.swing.JPanel jPBorrar;
    private javax.swing.JPanel jPCargar;
    private javax.swing.JPanel jPModificar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JLabel jlId;
    private javax.swing.JLabel jlIdModificar;
    private javax.swing.JTextField jtNombreMateria;
    private javax.swing.JLabel lbNombreCompleto;
    private javax.swing.JPanel panelNombreCompleto;
    private javax.swing.JRadioButton rbID;
    private javax.swing.JRadioButton rbLista;
    private javax.swing.JTextField tfBuscarId;
    // End of variables declaration//GEN-END:variables
}
