/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.util.List;
import sistema_gestion_alumnos.modelo.Alumno;
import sistema_gestion_alumnos.modelo.AlumnoData;
import sistema_gestion_alumnos.modelo.Conexion;
import sistema_gestion_alumnos.modelo.Inscripcion;
import sistema_gestion_alumnos.modelo.InscripcionData;

/**
 *
 * @author Lucas
 */
public class listadoMaterias extends javax.swing.JInternalFrame {

    /**
     * Creates new form listadoMaterias
     */
    
    private AlumnoData alumnoData;
    private InscripcionData inscripcionData;
    private Conexion con;

    public listadoMaterias() {
        initComponents();
        con = new Conexion();
        alumnoData = new AlumnoData(con);
        inscripcionData = new InscripcionData(con);
    }
    
    public void inicializarLista(){
        cbAlumnos.removeAllItems();
        List<Alumno> alumnos = alumnoData.obtenerAlumnos();
            boolean control;
            for(Alumno alumno : alumnos){
                control=true;
                for(int i=0;i<cbAlumnos.getItemCount();i++){
                    if(Integer.parseInt(cbAlumnos.getItemAt(i)) == alumno.getId()){
                        control=false;
                    }
                }
                if(control){
                    cbAlumnos.addItem(String.valueOf(alumno.getId()));
                }
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbAlumnos = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtMateriaXAlumno = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Listado de materias del alumno:");

        cbAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAlumnosActionPerformed(evt);
            }
        });

        jButton3.setText("Cerrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jtMateriaXAlumno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Materia", "Nota", "Activo"
            }
        ));
        jScrollPane1.setViewportView(jtMateriaXAlumno);

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.hide();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cbAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAlumnosActionPerformed
   
    }//GEN-LAST:event_cbAlumnosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        List<Inscripcion> inscripciones = inscripcionData.obtenerInscripciones();
        int cont_row=0;
        for (int i = 0; i < jtMateriaXAlumno.getRowCount(); i++) {
                for (int j = 0; j < jtMateriaXAlumno.getColumnCount(); j++) {
                    jtMateriaXAlumno.setValueAt("", i, j);
                }
            }
        for(Inscripcion inscripcion : inscripciones){
            if(inscripcion.getAlumno().getId() == Integer.parseInt(cbAlumnos.getSelectedItem().toString())){
                jtMateriaXAlumno.setValueAt(inscripcion.getMateria().getNombre(), cont_row, 0);
                jtMateriaXAlumno.setValueAt(inscripcion.getNota(), cont_row, 1);
                if(inscripcion.getAlumno().isActivo()){
                    jtMateriaXAlumno.setValueAt("Activo", cont_row, 2);
                }
                cont_row++;
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbAlumnos;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtMateriaXAlumno;
    // End of variables declaration//GEN-END:variables
}
