/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

/**
 *
 * @author Lucas
 */

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.LookAndFeel;
import javax.swing.UIManager;
import sistema_gestion_alumnos.modelo.Conexion;
import sistema_gestion_alumnos.modelo.Inscripcion;
import sistema_gestion_alumnos.modelo.InscripcionData;
import sistema_gestion_alumnos.modelo.Materia;
import sistema_gestion_alumnos.modelo.MateriaData;

public class listadoAlumnos extends javax.swing.JInternalFrame {

    /**
     * Creates new form listadoAlumnos
     */
    
    private MateriaData materiaData;
    private InscripcionData inscripcionData;
    private Conexion con;
    
    public listadoAlumnos() {
        initComponents();
        con = new Conexion();
        materiaData = new MateriaData(con);
        inscripcionData = new InscripcionData(con);

    } 
    
    public void inicializarLista(){
        cbMaterias.removeAllItems();
        List<Materia> materias = materiaData.obtenerMaterias();
            boolean control;
            for(Materia materia : materias){
                control=true;
                for(int i=0;i<cbMaterias.getItemCount();i++){
                    if(Integer.parseInt(cbMaterias.getItemAt(i)) == materia.getId()){
                        control=false;
                    }
                }
                if(control){
                    cbMaterias.addItem(String.valueOf(materia.getId()));
                }
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbMaterias = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtLista = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jlMateria = new javax.swing.JLabel();
        jbBuscar = new javax.swing.JButton();

        setName(""); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Seleccione una Materia:");

        cbMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMateriasActionPerformed(evt);
            }
        });

        jtLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre y apellido", "Materia", "Nota", "Activo"
            }
        ));
        jScrollPane1.setViewportView(jtLista);

        jButton1.setText("Cerrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jbBuscar.setText("Buscar");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jlMateria)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlMateria)
                    .addComponent(jbBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.hide();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMateriasActionPerformed
        jlMateria.setText(materiaData.buscarMateria(Integer.parseInt(cbMaterias.getSelectedItem().toString())).getNombre());
    }//GEN-LAST:event_cbMateriasActionPerformed

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        for (int i = 0; i < jtLista.getRowCount(); i++) {
                for (int j = 0; j < jtLista.getColumnCount(); j++) {
                    jtLista.setValueAt("", i, j);
                }
            }
        List<Inscripcion> inscripciones = inscripcionData.obtenerInscripciones();
        int cont_row=0,cont_col=0;
        for(Inscripcion inscripcion : inscripciones){
            if(inscripcion.getMateria().getId() == Integer.parseInt(cbMaterias.getSelectedItem().toString())){
                jtLista.setValueAt(inscripcion.getAlumno().getNombre_completo(), cont_col, cont_row);
                jtLista.setValueAt(inscripcion.getMateria().getNombre(), cont_col, cont_row+1);
                jtLista.setValueAt(inscripcion.getNota(), cont_col, cont_row+2);
                if(inscripcion.getAlumno().isActivo()){
                    jtLista.setValueAt("Activo", cont_col, cont_row+3);
                }
                else{
                    jtLista.setValueAt("Inactivo", cont_col, cont_row+3);
                }
                cont_col++;
            }
        }
    }//GEN-LAST:event_jbBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbMaterias;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JLabel jlMateria;
    private javax.swing.JTable jtLista;
    // End of variables declaration//GEN-END:variables
}
