/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.util.List;
import sistema_gestion_alumnos.modelo.Alumno;
import sistema_gestion_alumnos.modelo.AlumnoData;
import sistema_gestion_alumnos.modelo.Conexion;
import sistema_gestion_alumnos.modelo.Inscripcion;
import sistema_gestion_alumnos.modelo.InscripcionData;
import sistema_gestion_alumnos.modelo.Materia;
import sistema_gestion_alumnos.modelo.MateriaData;

/**
 *
 * @author Lucas
 */
public class nuevaNota extends javax.swing.JInternalFrame {
    
    private MateriaData materiaData;
    private InscripcionData inscripcionData;
    private AlumnoData alumnoData;
    private Conexion con;

    /**
     * Creates new form nuevaNota
     */
    public nuevaNota() {
        initComponents();
        con = new Conexion();
        materiaData = new MateriaData(con);
        inscripcionData = new InscripcionData(con);
        alumnoData = new AlumnoData(con);
    }
    
    public void inicializarLista(){
        cbAlumnos.removeAllItems();
        List<Alumno> alumnos = alumnoData.obtenerAlumnos();
            boolean control;
            for(Alumno alumno : alumnos){
                control=true;
                for(int i=0;i<cbAlumnos.getItemCount();i++){
                    if(Integer.parseInt(cbAlumnos.getItemAt(i)) == alumno.getId()){
                        control=false;
                    }
                }
                if(control){
                    cbAlumnos.addItem(String.valueOf(alumno.getId()));
                }
            }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jsNota = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbAlumnos = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtMaterias = new javax.swing.JTable();
        jbCambiarNota = new javax.swing.JButton();
        jbBuscar = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(741, 405));
        setMinimumSize(new java.awt.Dimension(741, 405));
        setPreferredSize(new java.awt.Dimension(741, 405));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jButton1.setText("Cerrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jsNota.setMajorTickSpacing(1);
        jsNota.setMinorTickSpacing(1);
        jsNota.setPaintTicks(true);
        jsNota.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jsNotaStateChanged(evt);
            }
        });

        jLabel1.setText("Nota");

        jLabel2.setText("Seleccione el alumno:");

        jLabel3.setText("Seleccione la nota:");

        jtMaterias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Materia", "Nota"
            }
        ));
        jScrollPane1.setViewportView(jtMaterias);

        jbCambiarNota.setText("Cambiar Nota");
        jbCambiarNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCambiarNotaActionPerformed(evt);
            }
        });

        jbBuscar.setText("Buscar");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(96, 96, 96)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jsNota, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                                    .addComponent(cbAlumnos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbBuscar)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbCambiarNota, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jsNota, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jbCambiarNota))
                .addGap(176, 176, 176))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.hide();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        if (evt.getSource()== jsNota.getChangeListeners())
        {
            jLabel1.setText(String.valueOf(jsNota.getValue()));
        }
    }//GEN-LAST:event_formMouseClicked

    private void jsNotaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jsNotaStateChanged
        jLabel1.setText("Nota: " + String.valueOf(jsNota.getValue()) + "%");
    }//GEN-LAST:event_jsNotaStateChanged

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        for (int i = 0; i < jtMaterias.getRowCount(); i++) {
                for (int j = 0; j < jtMaterias.getColumnCount(); j++) {
                    jtMaterias.setValueAt("", i, j);
                }
            }
        List<Inscripcion> inscripciones = inscripcionData.obtenerInscripciones();
        int cont_row=0,cont_col=0;
        for(Inscripcion inscripcion : inscripciones){
            if(inscripcion.getAlumno().getId() == Integer.parseInt(cbAlumnos.getSelectedItem().toString())){
                jtMaterias.setValueAt(inscripcion.getMateria().getNombre(), cont_row, 0);
                jtMaterias.setValueAt(inscripcion.getNota(), cont_row, 1);
                cont_row++;
            }
        }
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jbCambiarNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCambiarNotaActionPerformed
        Alumno alumno = alumnoData.buscarAlumno(Integer.parseInt(cbAlumnos.getSelectedItem().toString()));
        for(Inscripcion inscripcion : inscripcionData.obtenerInscripciones()){
            if(inscripcion.getAlumno().getNombre_completo().equals(alumno.getNombre_completo())){
                if(inscripcion.getMateria().getNombre().equals(jtMaterias.getValueAt(jtMaterias.getSelectedRow(), 0))){
                    Inscripcion notaCambiar = new Inscripcion(inscripcion.getAlumno(),inscripcion.getMateria(),jsNota.getValue()/10,inscripcion.getId());
                    inscripcionData.actualizarInscripcion(notaCambiar);
                }
            }
        }
    }//GEN-LAST:event_jbCambiarNotaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbAlumnos;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbCambiarNota;
    private javax.swing.JSlider jsNota;
    private javax.swing.JTable jtMaterias;
    // End of variables declaration//GEN-END:variables
}
